### PR TITLE
Python implementation of TrajGen, Version 1.0

### PR DESCRIPTION
**Pull request by tomcattiger1230**
Thanks for your interesting work. Here is my implementation using Python based on CasADi/qpOASES. If you test them well, you can add these codes in your codes, which may help others who would like to test the trajectory generator using Python.

### CODE REVIEW

**Comment by icsl-Jeon** [comment]
Thank you for your contribution! I have also been considering python implementation. 
I will check your source in the weekend and accept your pull request after a few checks. 

Thank you for your work!

Regards

**Comment by tomcattiger1230** [comment]
I am not sure why the check from Travis CI for C++ has the error. But it should be no influence on the Python scripts. @icsl-Jeon

**Comment by archit120** [comment]
This is so painful. I was on the verge of completing my own python implementation and just saw this PR. Nevertheless thanks a lot @tomcattigerkkk

**Comment by tomcattiger1230** [comment]
@archit120 
well. You may still try your version, since yours may have better performance or at least you provide an alternative to other people. :)
If there is any bug, please also let me know. Thanks.

**Pull request merged**
